### PR TITLE
Verify pkglist returned when errata is in more than one repository

### PR DESCRIPTION
**Pull request by kersommoura**
Verify that Pulp will returns right 'pkglist' if an erratum exists in
multiple repositories and user syncs multiple of these repositories.

https://pulp.plan.io/issues/4952
closes:#4952

### CODE REVIEW

**Comment by kersommoura** [comment]
Tested using a new fixture set. See: https://github.com/PulpQE/pulp-fixtures/pull/123

**Comment by bherrin3** [comment]
@kersommoura I am getting the same failure as CI on my local `make all` from this PR as well, FYI.

**Comment by bherrin3** [comment]
@kersommoura Ran locally in the suite without issue. Once the File conflict is resolved, let me know and I will merge it!

**Comment by kersommoura** [comment]
Ci failure is due to: https://gitlab.com/pycqa/flake8-docstrings/issues/36

**Pull request merged**
