### PR TITLE
Adding check for modular RPM upload is_modular tags

### PR DESCRIPTION
**Pull request by bherrin3**
## Problem

Issue #4869 updates the ``DISTAG`` check to a new backwards compatible check for ``is_modular`` for RPM uploads.

## Updates
Adding verification for RPM uploads with and without ``is_modular`` to ensure the RPM tags are being read correctly.

## Notes

* RM 4869 is not yet merged
* The test fixture RPM is current taken from the F30 Modular RPM repository. 
* Using a sane baseline to ensure the tests functions. Later updating the fixture to a self-built modular RPM, if possible (time).

## References

* https://pulp.plan.io/issues/4869
* https://github.com/pulp/pulp_rpm/pull/1368

closes #4930

### CODE REVIEW

**Comment by kersommoura** [comment]
@bherrin3, as we talk lets suggest this PR to be run locally with the code related to the #4869. Before we merge in here, to avoid extra troubleshooting later on. Good job.

**Comment by bherrin3** [comment]
@kersommoura ideally wait for #202 to merge before merging this one, please. :)

**Comment by bherrin3** [comment]
> @bherrin3, as we talked lets suggest this PR to be run locally with the code related to the #4869. Before we merge in here, to avoid extra troubleshooting later on. Good job.

Other issues were investigated and this helped with that investigation.

Source PR is now merged and this can be merged into CI and has been tested to function before merge.

**Comment by bherrin3** [comment]
@kersommoura @rochacbruno re-based. It will now `fail` unless we rebuild the p2 RPMs with the CI job as the ticket is set to ``MODIFIED``, but the RPMs will not have been built from 2-master until tonight

**Comment by bherrin3** [comment]
Note: Just updated docstring meta that was inaccurate (removal of 1 line in constants).

**Pull request merged**
